/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./components/**/*.{js,jsx,ts,tsx}", "./app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: 'class', // enables dark mode using 'dark' class
  theme: {
    extend: {
      colors: {
        background: "#ffffff",
        foreground: "#0f1419",
        card: "#f7f8f8",
        "card-foreground": "#0f1419",
        popover: "#ffffff",
        "popover-foreground": "#0f1419",
        primary: "#1e9df1",
        "primary-foreground": "#ffffff",
        secondary: "#0f1419",
        "secondary-foreground": "#ffffff",
        muted: "#e5e5e6",
        "muted-foreground": "#0f1419",
        accent: "#e3ecf6",
        "accent-foreground": "#1e9df1",
        destructive: "#f4212e",
        "destructive-foreground": "#ffffff",
        border: "#e1eaef",
        input: "#f7f9fa",
        ring: "#1da1f2",
        "chart-1": "#1e9df1",
        "chart-2": "#00b87a",
        "chart-3": "#f7b928",
        "chart-4": "#17bf63",
        "chart-5": "#e0245e",
        sidebar: "#f7f8f8",
        "sidebar-foreground": "#0f1419",
        "sidebar-primary": "#1e9df1",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e3ecf6",
        "sidebar-accent-foreground": "#1e9df1",
        "sidebar-border": "#e1e8ed",
        "sidebar-ring": "#1da1f2",

        // Dark theme
        dark: {
          background: "#000000",
          foreground: "#e7e9ea",
          card: "#17181c",
          "card-foreground": "#d9d9d9",
          popover: "#000000",
          "popover-foreground": "#e7e9ea",
          primary: "#1c9cf0",
          "primary-foreground": "#ffffff",
          secondary: "#f0f3f4",
          "secondary-foreground": "#0f1419",
          muted: "#181818",
          "muted-foreground": "#72767a",
          accent: "#061622",
          "accent-foreground": "#1c9cf0",
          destructive: "#f4212e",
          "destructive-foreground": "#ffffff",
          border: "#242628",
          input: "#22303c",
          ring: "#1da1f2",
          "chart-1": "#1e9df1",
          "chart-2": "#00b87a",
          "chart-3": "#f7b928",
          "chart-4": "#17bf63",
          "chart-5": "#e0245e",
          sidebar: "#17181c",
          "sidebar-foreground": "#d9d9d9",
          "sidebar-primary": "#1da1f2",
          "sidebar-primary-foreground": "#ffffff",
          "sidebar-accent": "#061622",
          "sidebar-accent-foreground": "#1c9cf0",
          "sidebar-border": "#38444d",
          "sidebar-ring": "#1da1f2",
        },
      },
      fontFamily: {
        sans: ["Open Sans", "sans-serif"],
        serif: ["Georgia", "serif"],
        mono: ["Menlo", "monospace"],
      },
      borderRadius: {
        sm: "1rem",
        md: "1.1rem",
        lg: "1.3rem",
        xl: "1.5rem",
      },
      spacing: {
        DEFAULT: "0.25rem",
      },
      boxShadow: {
        "2xs": "0px 2px 0px 0px rgba(0,0,0,0)",
        xs: "0px 2px 0px 0px rgba(0,0,0,0)",
        sm: "0px 2px 0px 0px rgba(0,0,0,0), 0px 1px 2px -1px rgba(0,0,0,0)",
        DEFAULT: "0px 2px 0px 0px rgba(0,0,0,0), 0px 1px 2px -1px rgba(0,0,0,0)",
        md: "0px 2px 0px 0px rgba(0,0,0,0), 0px 2px 4px -1px rgba(0,0,0,0)",
        lg: "0px 2px 0px 0px rgba(0,0,0,0), 0px 4px 6px -1px rgba(0,0,0,0)",
        xl: "0px 2px 0px 0px rgba(0,0,0,0), 0px 8px 10px -1px rgba(0,0,0,0)",
        "2xl": "0px 2px 0px 0px rgba(0,0,0,0)",
      },
    },
  },
  plugins: [],
};
